import 'dart:convert';
import 'dart:typed_data';
import 'package:genui/genui.dart';
import 'package:json_schema_builder/json_schema_builder.dart';
import '../../features/background/widgets/background_image_widget.dart';
import '../../app.dart';

final backgroundImageItem = CatalogItem(
  name: 'BackgroundImage',
  dataSchema: S.object(
    properties: {
      'imageUrl': S.string(
        description:
            'URL of the background image. Use "generated" if image was generated by ImageGen, null to show gradient, or a network URL.',
      ),
      'description': S.string(
          description: 'Description of the background theme/style'),
    },
    required: ['description'], // imageUrl is optional
  ),
  widgetBuilder: (context) {
    final data = context.data as Map<String, dynamic>;
    // Handle both string and null imageUrl
    final imageUrlValue = data['imageUrl'];
    String? imageUrl;
    Uint8List? imageData;

    if (imageUrlValue is String) {
      if (imageUrlValue == 'generated') {
        // Load image directly from ImagenService
        final imagenService = globalImagenService;
        if (imagenService != null &&
            imagenService.generatedImageData != null) {
          imageData = imagenService.generatedImageData;
          // Create a data URL from the image data
          final base64Image = base64Encode(imageData!.toList());
          imageUrl = 'data:image/png;base64,$base64Image';
        } else {
          imageUrl = null; // Fallback to gradient
        }
      } else {
        imageUrl = imageUrlValue;
      }
    } else {
      imageUrl = null;
    }

    return BackgroundImageWidget(
      imageUrl: imageUrl,
      description: data['description'] as String?,
      imageData: imageData,
    );
  },
);
